# This rule is not used by the project pg-database-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the lab.pglab.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pg-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: pgdatabase-editor-role
rules:
- apiGroups:
  - lab.pglab.dev
  resources:
  - pgdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.pglab.dev
  resources:
  - pgdatabases/status
  verbs:
  - get
